### ISSUE TITLE
Can't compile with Xcode 9.3, iOS 11.3

### ISSUE THREAD

**Issue by MichaelDylan77** [xmartlabs/Bender#103]
After installing from the cocopod, I get this error on iOS 11.3, Xcode 9.3. Bender version 0.4.1

`Type of expression is ambiguous without more context`

It appears in the Convolution layer, as well as the DepthwiseConvolution.

Convolution.swift: line 114

![screen shot 2018-04-07 at 4 42 39 pm](https://user-images.githubusercontent.com/30844227/38460603-bc5457e6-3a82-11e8-8455-568c45f18616.png)

and again in DepthwiseConvolution.swift: line 41

![screen shot 2018-04-07 at 4 43 25 pm](https://user-images.githubusercontent.com/30844227/38460614-f011ac82-3a82-11e8-837e-0fe39071ac76.png)

Any ideas on how to get this working?

**Comment by MichaelDylan77** [comment]
Gotcha. That’s pretty much what I figured. I’ve been playing around with the MPSCNNConvolutionDataSource as well. Thanks for the input!

**Comment by mats-claassen** [comment]
You can try it on master now

**Comment by MichaelDylan77** [comment]
Will try it tomorrow afternoon and report back. Thanks man!
