### ISSUE TITLE
Tests fail in iOS 11.3.1 on iPhone 8+

### ISSUE THREAD

**Issue by mats-claassen** [xmartlabs/Bender#110]
In iOS 11.3.1 the tests for the `Concat` and `LocalResponseNorm` layers fail in iPhone 8 and iPhone X.
They work in iOS 11.3 (to my understanding) and also if run on iPhone 7 or below.

I am not sure this is a Bender or an iOS issue.

**Comment by PIRANAVARUBAN** [comment]
Bug in iPhoneX in iOS 11.3

**Comment by PIRANAVARUBAN** [comment]
Any update about this Issue

**Comment by mats-claassen** [comment]
I haven't tested this on an iPhone 8 on Xcode 9.4. We reported the issue to Apple.

**Comment by hollance** [comment]
FWIW I noticed similar issues with my own compute kernels on the iOS 11.3 beta on A11 devices.

**Comment by mats-claassen** [comment]
Thanks for the comment @hollance. 

I haven't tried this on iOS 12 either but as you said this should be fixed in iOS 12. However, we were told that they might not fix it for iOS 11.x. It might be worth to see if changing `ushort's` to `uint's` fixes our issues.
