### ISSUE TITLE
dilated convolution layer

### ISSUE THREAD

**Issue by gwangsc** [xmartlabs/Bender#15]
Hi, dilated convolution (https://github.com/fyu/dilation) is very useful in recently developed networks such as enet (https://github.com/e-lab/ENet-training). 
Could you please add support to dilated convolution?

**Comment by mats-claassen** [comment]
Hi @gwangsc we will have a look at it. There are some other things in the backlog but we definitely want to keep adding new layers!

**Comment by bryant1410** [comment]
@gwangsc we are also open to contributions if you want to implement the feature youself

**Comment by liamnaks** [comment]
New RNN performance shaders added to Metal in iOS 11.0 beta, should be fun to work with!

**Comment by gwangsc** [comment]
Yep. Saw the keynote. It is pretty cool. 
But it would be good to have those missing layers implemented, for older devices which may not support 11.0 and Metal2.
