### ISSUE TITLE
No such module 'SwiftProtobuf'

### ISSUE THREAD

**Issue by kalli8** [xmartlabs/Bender#20]
I had to manually add the SwiftProtobuf dependency with Pods which worked fine, but I can't get the example project to run as it looks like Bender is imported directly into the project.

**Comment by mats-claassen** [comment]
There is a step missing in the Readme. We install SwiftProtobuf using Carthage so you should run `carthage update --platform iOS` before you can run the examples.

**Comment by kalli8** [comment]
I get 
$ carthage update -- platform ios
Failed to read file or folder at /Users/username/Bender/Example/Cartfile: Error Domain=NSCocoaErrorDomain Code=260 "The file “Cartfile” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/username/Bender/Example/Cartfile, NSUnderlyingError=0x7fca61151ed0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}

**Comment by mats-claassen** [comment]
The Cartfile is not in the `Example` folder. It is at the root folder
