### ISSUE TITLE
clarification tensorflow + magenta .mag file / cyclic redundancy problem 

### ISSUE THREAD

**Issue by johndpope** [xmartlabs/Bender#21]
Awesome job on this project.

I'm looking to extend functionality over to support magenta.
Yes, granted current library isn't rigged up to do this. 
https://github.com/tensorflow/magenta

I added a .mag file from google's tensorflow / magenta project.

They are using a metagraph file - this contains a few extra protobuf files needed from tensorflow.
Tensorflow_MetaGraphDef /MetaInfoDef and others etc

(Side Note - feel free to cherry pick this stash - my branch includes all files 
https://github.com/johndpope/swift-grpc-tensorflow/tree/0.0.2
If you ever find yourself wanting to programmatically convert proto files - you may also want to checkout  https://github.com/nubbel/swift-tensorflow/blob/master/RUNME.sh )

 so I rigged up a new wrapper to extract the graph def  from a metagraphdef
https://github.com/johndpope/Bender/

   if let path = Bundle.main.path(forResource: "attention_rnn", ofType: "mag"){
            
            let model = try? Data(contentsOf:URL(fileURLWithPath: path))
            
            // pull apart inception model.
            let myGraphProto = try? Tensorflow_Magenta_GeneratorBundle.init(serializedData:model!)
            
            let metaGraphData = myGraphProto!.metagraphFile
            
            let graph1 = try? Tensorflow_MetaGraphDef.init(serializedData:metaGraphData)
            print("graph1:",graph1)
            https://gist.github.com/johndpope/7be8b9b365050ad9615938ae15c36ac4
           
            // this errors.
              var graph =  TFGraph(graphDef: graph1.graphDef)
        }
       
could there be  a specific nip and tuck that could be done to get this to work?
https://gist.github.com/johndpope/7be8b9b365050ad9615938ae15c36ac4

related
https://github.com/tensorflow/magenta/issues/710

**Comment by bryant1410** [comment]
Thanks! :smile:

You have a Metagraph file, but you have a whole checkpoint? If you do, consider using [benderthon](https://github.com/xmartlabs/benderthon), as described in the docs, so you can convert it to a frozen and small graph.

**Comment by bryant1410** [comment]
I don't know much about magenta and .mag files, but the file format seems to be a protobuf with GeneratorBundle as a protocol, defined in [generator.proto](https://github.com/tensorflow/magenta/blob/8a84f7da776b35f7ea6da8f432f4174dfef9d7d2/magenta/protobuf/generator.proto#L59). To simplify the process, you can load that with benderthon, forking it and then freezing and saving the graph.

With respect to the cyclic problem, it seems to be related to the RNNs. Where does it manifest exactly?

**Comment by bryant1410** [comment]
@johndpope can you provide a frozen graph so it's easier for us (and for others) to test it?

**Comment by johndpope** [comment]
I'm digging through tensorflow magenta forums.
all my code is pushed to master here ->
https://github.com/johndpope/Bender/

I'll keep digging for check point file + meta file.

**Comment by johndpope** [comment]
https://github.com/tensorflow/magenta/tree/master/magenta/models/melody_rnn#creating-a-bundle-file

Creating a Bundle File

The bundle format is a convenient way of combining the model checkpoint, metagraph, and some metadata about the model into a single file.

https://github.com/tensorflow/magenta/blob/master/magenta/protobuf/generator.proto

**Comment by johndpope** [comment]
from looking at code under the hood of bender - it seems more appropriate for image stuff rather than vanilla rnn / lstm tensorflow models. going to close this.

**Comment by johndpope** [comment]
I think this wsas root of problem.
**TF graph must be cycle free (cycles are generally created due to control flow ops like if, while, map, etc.)**
https://github.com/tf-coreml/tf-coreml
