### ISSUE TITLE
Convert model from Tensor flow

### ISSUE THREAD

**Issue by hoangtuanfithou** [xmartlabs/Bender#43]
Dear @bryant1410 ,

I want to 
1. Trained 1 more flower using : https://www.tensorflow.org/tutorials/image_retraining
2. then using your guide to import model from step 1 to use with Blender but I can not convert and import
https://github.com/xmartlabs/Bender/blob/master/Documentation/Importing.md
-> 
benderthon tf-freeze checkpoint_path.ckpt graph_with_weights.pb Output_Node_Name
what is checkpoint_path.ckpt where I can get it, what is out put of the script ?
3. please support if you have time

Thanks so much

**Comment by bryant1410** [comment]
You need to [save your TF model to generate a checkpoint file](https://www.tensorflow.org/programmers_guide/variables#saving_and_restoring) (that is the "checkpoint_path.ckpt", the checkpoint files prefix path that you used to save it).

The output is the name of the output node. It can be obtained from the network, based on the name of the node that is the output of the network.

**Comment by bryant1410** [comment]
Ok, I'm closing now. If you still have the issue, please comment.
