### ISSUE TITLE
Correct Installation?

### ISSUE THREAD

**Issue by derdav3** [xmartlabs/Bender#45]
Noob question: Downloading the git and installing the example project using the cartfile works, but when incorporating Bender into my own project the import clearly fails. I added the lines

```
platform :ios, '10.0'
pod 'MetalBender', :git => 'https://github.com/xmartlabs/Bender.git'
```

to my Podfile, but importing 'Bender' fails with the "No such module". Sorry if this is non-bender specific as I don't really know Swift :)

**Comment by dernster** [comment]
Hey @derdav3! Can you show me your entire podfile? Also, are you opening the workspace or the project? Once you execute `pod install`, you should work in your workspace NOT your project.

**Comment by derdav3** [comment]
Sure:
```
# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'FrontPortrait' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FrontPortrait
  pod 'MetalBender', :git => 'https://github.com/xmartlabs/Bender.git'

  target 'FrontPortraitTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FrontPortraitUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

And yes - I'm working with the workspace.
Thanks! :)

**Comment by dernster** [comment]
@derdav3 Make sure in your Swift code you're importing `MetalBender` not just `Bender`. Otherwise if you share with us your project, we can take a look.

**Comment by derdav3** [comment]
@dernster Ah so I have to pod install, **then compile**, then import.. lol coming from python this is not that intuitive. Now the `import MetalBender` works, but `import Bender` still fails... anything else I have to consider?

I don't really have a project to show. I'm coming from developing Tensorflow models, and want to know how I could implement those for the iPhone. atm I just have a TF protobuf graph and want to get a fresh app to compile

**Comment by dernster** [comment]
@derdav3 Yes, that's correct. You should import only `MetalBender`. Importing `Bender` **is not** supposed to work :)

**Comment by derdav3** [comment]
ah lol I thought your "MetalBender not just Bender" meant I have to import both. Thanks for the input... gotta learn Swift now :smile:
