### ISSUE TITLE
Can't Build on xcode 8 [Macpods]

### ISSUE THREAD

**Issue by geoeo** [xmartlabs/Bender#63]
Hey I can't build the project in xcode 8.
I can build in xcode 9 beta BUT when I try to deploy to a actual device I get the same error
This is the error message is:

Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_MPSCNNSpatialNormalization", referenced from:
      objc-class-ref in SpatialNorm.o
  "_OBJC_CLASS_$_MPSCNNSoftMax", referenced from:
      objc-class-ref in Softmax.o
  "_OBJC_CLASS_$_MPSImageLanczosScale", referenced from:
      objc-class-ref in Scale.o
      objc-class-ref in Start.o
  "_OBJC_CLASS_$_MPSCNNPoolingMax", referenced from:
      objc-class-ref in Pooling.o
  "_OBJC_CLASS_$_MPSCNNPoolingAverage", referenced from:
      objc-class-ref in Pooling.o
  "_OBJC_CLASS_$_MPSTemporaryImage", referenced from:
      objc-class-ref in ConvTranspose.o
      objc-class-ref in Start.o
  "_OBJC_CLASS_$_MPSImageDescriptor", referenced from:
      objc-class-ref in Add.o
      objc-class-ref in BGRAtoRGBA.o
      objc-class-ref in Concat-2F047EC0A4EC20B2.o
      objc-class-ref in Convolution.o
      objc-class-ref in ConvTranspose.o
      objc-class-ref in Crop.o
      objc-class-ref in FullyConnected.o
      ...
  "_OBJC_CLASS_$_MPSCNNConvolution", referenced from:
      objc-class-ref in Convolution.o
  "_OBJC_CLASS_$_MPSImage", referenced from:
      objc-class-ref in Add.o
      objc-class-ref in BGRAtoRGBA.o
      objc-class-ref in Concat-2F047EC0A4EC20B2.o
      objc-class-ref in Convolution.o
      objc-class-ref in ConvTranspose.o
      objc-class-ref in Crop.o
      objc-class-ref in FullyConnected.o
      ...
  "_OBJC_CLASS_$_MPSCNNNeuronSigmoid", referenced from:
      objc-class-ref in ActivationNeuronType.o
  "_OBJC_CLASS_$_MPSCNNConvolutionDescriptor", referenced from:
      objc-class-ref in Convolution.o
      objc-class-ref in FullyConnected.o
  "_OBJC_CLASS_$_MPSCNNNeuron", referenced from:
      objc-class-ref in ActivationNeuronType.o
      objc-class-ref in Neuron.o
  "_OBJC_CLASS_$_MPSCNNFullyConnected", referenced from:
      objc-class-ref in FullyConnected.o
  "_OBJC_CLASS_$_MPSCNNNeuronReLU", referenced from:
      objc-class-ref in ActivationNeuronType.o
  "_OBJC_CLASS_$_MPSCNNNeuronLinear", referenced from:
      objc-class-ref in ActivationNeuronType.o
  "_OBJC_CLASS_$_MPSCNNPooling", referenced from:
      objc-class-ref in Pooling.o
  "_OBJC_CLASS_$_MPSCNNNeuronTanH", referenced from:
      objc-class-ref in ActivationNeuronType.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by bryant1410** [comment]
What problem are you having with Xcode 8? Are you [using Carthage](https://github.com/xmartlabs/Bender#examples)? Have you added all frameworks to the target?

**Comment by geoeo** [comment]
No, I am using Mac Pods. My Podfile is taken from the Installation Section:

# Uncomment this line to define a global platform for your project
platform :ios, '10.0'

target 'Classifier_Benderthon' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Classifier_Benderthon
  pod 'MetalBender', :git => 'https://github.com/xmartlabs/Bender.git'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.2'
        end
    end
  end

end

I assumed it should work like this out of the box.

**Comment by geoeo** [comment]
I switched to carthage and it builds fine now.

**Comment by bryant1410** [comment]
Oh, but not this project, but a project that uses Bender as a dependency. Ok.

**Comment by geoeo** [comment]
Yes sorry. I trying to use it as a library for a classification app

**Comment by bryant1410** [comment]
Fixed by #66
