### ISSUE TITLE
How to use model with 2 input parameters?

### ISSUE THREAD

**Issue by czater** [xmartlabs/Bender#86]
I have style transfer model that have 2 input parameters - image and style number. Where can I add style number parameter? In .run there is only place fot image and completionHandler.

**Comment by czater** [comment]
Anyone?

**Comment by bryant1410** [comment]
Unfortunately, this is not currently supported.

This could be worked around with custom layers, but they can only be added in pre or post processing stages. Also changing the Start node with some custom one, but operations cannot return more than one output, so it's useless. Also, there's no way to take only some part of the input in the middle of the net, which would be useful if concatenating the 2 inputs.

As we don't have an ETA for this, what you can do is to fork the library and hardcode the different inputs for the different operations that use them.
